### ISSUE TITLE
Update to seaborn 0.9.0?

### ISSUE THREAD

**Issue by justbennet** [maartenmennes/ICA-AROMA#33]
We were getting warnings from seaborn about deprecated functions.

Those were reported by the Pandas team and others to the seaborn maintainer, who fixed them in release 0.9.0.  The errors were

```
Traceback (most recent call last):
  File "/usr/local/aroma/ICA-AROMA-a629eb70/ICA_AROMA.py", line 226, in <module>
    outDir)
  File "/usr/local/aroma/ICA-AROMA-a629eb70/classification_plots.py", line 170, in classification_plot
    hist_kws={'alpha': 0.2})
  File "/usr/local/aroma/python/lib/python2.7/site-packages/seaborn/distributions.py", line 208, in distplot
    bins = min(_freedman_diaconis_bins(a), 50)
  File "/usr/local/aroma/python/lib/python2.7/site-packages/seaborn/distributions.py", line 29, in _freedman_diaconis_bins
    h = 2 * iqr(a) / (len(a) ** (1 / 3))
TypeError: len() of unsized object
/usr/local/aroma/python/lib/python2.7/site-packages/seaborn/categorical.py:462: FutureWarning: remove_na is deprecated and is a private function. Do not use.
  box_data = remove_na(group_data)
/usr/local/aroma/python/lib/python2.7/site-packages/matplotlib/axes/_axes.py:6448: UserWarning: The 'normed' kwarg is deprecated, and has been replaced by the 'density' kwarg.
```

Perhaps you would consider updating the requirement from seaborn 0.8.0 to 0.9.0, if that doesn't introduce additional issues?

**Comment by maartenmennes** [comment]
addressed in ea166b937f7aa37014257c0f555d131c3542a22b
