### ISSUE TITLE
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

### ISSUE THREAD

**Issue by GerardYu** [maartenmennes/ICA-AROMA#40]
Hi Maarten,
I found out that if i specify the feat folder instead of the individual files (like in the previous issue i've raised), i could a little progress further with the ICA-AROMA script, though it still could not be completed

--------------- 'ICA-based Automatic Removal Of Motion Artifacts' ---------------

Step 1) MELODIC
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
  - extracting the CSF & Edge fraction features
  - extracting the Maximum RP correlation feature
  - extracting the High-frequency content feature
  - classification
Traceback (most recent call last):
  File "../ICA-AROMA/ICA_AROMA.py", line 226, in <module>
    outDir)
  File "/bcs/projects/gerard_TDCSCogTraining/cross/REST/ICA-AROMA/classification_plots.py", line 6, in classification_plot
    import pandas as pd
  File "/home/gerard/.local/lib/python2.7/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "/home/gerard/.local/lib/python2.7/site-packages/pandas/_libs/__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "__init__.pxd", line 872, in init pandas._libs.tslib
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

**Comment by maartenmennes** [comment]
hmm, we haven't seen this error before. Have you got the latest versions of numpy and pandas installend?

**Comment by GerardYu** [comment]
I reinstalled numpy and pandas and it worked now. 
thanks!
