### ISSUE TITLE
Error running ICA-AROMA

### ISSUE THREAD

**Issue by stephanwu89** [maartenmennes/ICA-AROMA#51]
Dear all,

I ran ICA-AROMA for several subjects and everything worked well.
For some subjects I encounter the following error, although they are very similar to the ones where ICA-AROMA works fine:

------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: subtraction: incompatible matrix dimensions: 0x0 and 1x0
Traceback (most recent call last):
  File "/Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/ICA_AROMA.py", line 204, in <module>
    aromafunc.runICA(fslDir, inFile, outDir, melDir, mask, dim, TR)
  File "/Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/ICA_AROMA_functions.py", line 94, in runICA
    nrICs = int(float(subprocess.getoutput(cmd)))
ValueError: could not convert string to float: Image Exception : #63 :: No image files match: /Users/neurolab/Desktop/Drmed/CART_Code_rearranged_concat_prep/derivatives/participant/fmriprep/sub-10/ses-5/func/ICA_AROMA/melodic.ica/melodic_IC
No ima

I couldn't find out why this is happening,

Best,

**Comment by maartenmennes** [comment]
Hi Stephan,
it looks that for these subject the melodic run failed? Perhaps it ran out of memory and you did not notice.

**Comment by stephanwu89** [comment]
Thanks a lot for your reply.

That error looks different:

------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
  - extracting the CSF & Edge fraction features
  - extracting the Maximum RP correlation feature
  - extracting the High-frequency content feature
  - classification
Found 1 file(s)
Found 20 head motion-related components in a total of 20 components.
Traceback (most recent call last):
  File "/Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/ICA_AROMA.py", line 229, in <module>
    outDir)
  File "/Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/classification_plots.py", line 172, in classification_plot
    hist_kws={'alpha': 0.2})
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 231, in distplot
    kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 691, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 294, in _univariate_kdeplot
    x, y = _scipy_univariate_kde(data, bw, gridsize, cut, clip)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 366, in _scipy_univariate_kde
    kde = stats.gaussian_kde(data, bw_method=bw)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/stats/kde.py", line 208, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/stats/kde.py", line 540, in set_bandwidth
    self._compute_covariance()
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/stats/kde.py", line 552, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/linalg/basic.py", line 974, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix

**Comment by maartenmennes** [comment]
yes: "Found 20 head motion-related components in a total of 20 components."

i.e., all of your components are marked to be removed from the data, nothing would be left... Something is likely off, either in your data itself (e.g., a severe artifact) or in the analysis path (e.g., registration failed so your brain data is not on the standard brain)

**Comment by stephanwu89** [comment]
or because I set the criteria to -dim 20?

**Comment by maartenmennes** [comment]
potentially, but unlikely. A good indication could be to see how many components melodic returns if you don't set the dimensionality to 20. Is there a particular reason why you did this? We typically recommend to not set the dimensionality for denoising purposes (unless you have a huge number of volumes e.g., in the case of multiband data).

**Comment by stephanwu89** [comment]
without the command it works:

------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
  - extracting the CSF & Edge fraction features
  - extracting the Maximum RP correlation feature
  - extracting the High-frequency content feature
  - classification
Found 1 file(s)
Found 49 head motion-related components in a total of 51 components.
Step 3) Data denoising

----------------------------------- Finished -----------------------------------

**Comment by stephanwu89** [comment]
But I am still having the error from above:
runs for about 5 seconds and then brings up this error (available memory 64GB and same command runs fine for other subjects)

--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC
libc++abi.dylib: terminating with uncaught exception of type std::logic_error: subtraction: incompatible matrix dimensions: 0x0 and 1x0
Traceback (most recent call last):
  File "/Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/ICA_AROMA.py", line 204, in <module>
    aromafunc.runICA(fslDir, inFile, outDir, melDir, mask, dim, TR)
  File "/Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/ICA_AROMA_functions.py", line 94, in runICA
    nrICs = int(float(subprocess.getoutput(cmd)))
ValueError: could not convert string to float: Image Exception : #63 :: No image files match: /Users/neurolab/Desktop/Drmed/CART_Code_rearranged_concat_prep/derivatives/participant/fmriprep/sub-1/ses-1/func/ICA_AROMA_auto/melodic.ica/melodic_IC
No

and it is not a memory error.

**Comment by maartenmennes** [comment]
This error is related to FSL's melodic and not ICA-AROMA. I suspect something is off with your input data or the mask that is being calculated. Have you looked at the raw data? Have you tried running melodic directly on those data?

**Comment by stephanwu89** [comment]
The input data looks fine. And running directly with melodic works.

**Comment by maartenmennes** [comment]
Do the components look sensible? You can now also try to run AROMA where you provide the melodic directory you just created. If you run melodic as part of FEAT, AROMA will detect the .ica directory and not rerun melodic.

**Comment by stephanwu89** [comment]
How would I provide the output directory to AROMA? 

for ((i = 1; i < 2; i++));for ((ses = 1; ses < 8; ses++));
python2.7 /Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/ICA_AROMA.py -in /Users/neurolab/Desktop/Drmed/CART_Code_rearranged_concat_prep/derivatives/participant/fmriprep/sub-${i}/ses-${ses}/func/sub-${i}_ses-${ses}_task-rest_run-3_space-MNI152NLin2009cAsym_desc-preproc_bold_skipped_5_smoothed_6.nii.gz  -out  /Users/neurolab/Desktop/Drmed/CART_Code_rearranged_concat_prep/derivatives/participant/fmriprep/sub-${i}/ses-${ses}/func/sub-1_ses-1_task-rest_run-3_space-MNI152NLin2009cAsym_desc-preproc_bold_skipped_5_smoothed_6.ica -mc /Users/neurolab/Desktop/Drmed/CART_Code_rearranged_concat_prep/sub-${i}/ses-${ses}/func/sub-${i}_ses-${ses}_task-rest_run-3_bold_mcf.par

sub-1_ses-1_task-rest_run-3_space-MNI152NLin2009cAsym_desc-preproc_bold_skipped_5_smoothed_6.ica  is the created output directory.

**Comment by maartenmennes** [comment]
use the -md option. The -out option is for the directory where you want AROMA to save its results...

python2.7 /Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/ICA_AROMA.py --help

gives your more info...

**Comment by stephanwu89** [comment]
ah, great. Could not find that command in the manual.
Coming back to my post above:
...Found 49 head motion-related components in a total of 51 components.. means only 2 components are left in the end?
Isn't that too little?
I was putting dim to 20 because, I had the feeling ICA-AROMA is denoting out too many components. In the end my correlation for my bold signal seemed to be very high.

What would be your thoughts on that?

**Comment by stephanwu89** [comment]
running ICA-AROMA after melodic gives the following error:


------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC
  - The existing/specified MELODIC directory will be used.
  - The MELODIC directory does not contain the required 'stats' folder. Mixture modeling on the Z-statistical maps will be run.
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
  - extracting the CSF & Edge fraction features
     - The spatial map of component 1 is empty. Please check!
     - The spatial map of component 2 is empty. Please check!
     - The spatial map of component 3 is empty. Please check!
     - The spatial map of component 4 is empty. Please check!
     - The spatial map of component 5 is empty. Please check!
     - The spatial map of component 6 is empty. Please check!
     - The spatial map of component 7 is empty. Please check!
     - The spatial map of component 8 is empty. Please check!
     - The spatial map of component 9 is empty. Please check!
     - The spatial map of component 10 is empty. Please check!
     - The spatial map of component 11 is empty. Please check!
     - The spatial map of component 12 is empty. Please check!
     - The spatial map of component 13 is empty. Please check!
     - The spatial map of component 14 is empty. Please check!
     - The spatial map of component 15 is empty. Please check!
     - The spatial map of component 16 is empty. Please check!
     - The spatial map of component 17 is empty. Please check!
     - The spatial map of component 18 is empty. Please check!
     - The spatial map of component 19 is empty. Please check!
     - The spatial map of component 20 is empty. Please check!
     - The spatial map of component 21 is empty. Please check!
     - The spatial map of component 22 is empty. Please check!
     - The spatial map of component 23 is empty. Please check!
     - The spatial map of component 24 is empty. Please check!
     - The spatial map of component 25 is empty. Please check!
     - The spatial map of component 26 is empty. Please check!
     - The spatial map of component 27 is empty. Please check!
     - The spatial map of component 28 is empty. Please check!
     - The spatial map of component 29 is empty. Please check!
     - The spatial map of component 30 is empty. Please check!
     - The spatial map of component 31 is empty. Please check!
     - The spatial map of component 32 is empty. Please check!
     - The spatial map of component 33 is empty. Please check!
     - The spatial map of component 34 is empty. Please check!
     - The spatial map of component 35 is empty. Please check!
     - The spatial map of component 36 is empty. Please check!
     - The spatial map of component 37 is empty. Please check!
     - The spatial map of component 38 is empty. Please check!
     - The spatial map of component 39 is empty. Please check!
     - The spatial map of component 40 is empty. Please check!
     - The spatial map of component 41 is empty. Please check!
     - The spatial map of component 42 is empty. Please check!
     - The spatial map of component 43 is empty. Please check!
     - The spatial map of component 44 is empty. Please check!
     - The spatial map of component 45 is empty. Please check!
     - The spatial map of component 46 is empty. Please check!
     - The spatial map of component 47 is empty. Please check!
     - The spatial map of component 48 is empty. Please check!
     - The spatial map of component 49 is empty. Please check!
     - The spatial map of component 50 is empty. Please check!
     - The spatial map of component 51 is empty. Please check!
     - The spatial map of component 52 is empty. Please check!
     - The spatial map of component 53 is empty. Please check!
     - The spatial map of component 54 is empty. Please check!
     - The spatial map of component 55 is empty. Please check!
     - The spatial map of component 56 is empty. Please check!
     - The spatial map of component 57 is empty. Please check!
     - The spatial map of component 58 is empty. Please check!
     - The spatial map of component 59 is empty. Please check!
     - The spatial map of component 60 is empty. Please check!
     - The spatial map of component 61 is empty. Please check!
     - The spatial map of component 62 is empty. Please check!
     - The spatial map of component 63 is empty. Please check!
     - The spatial map of component 64 is empty. Please check!
  - extracting the Maximum RP correlation feature
  - extracting the High-frequency content feature
  - classification
Found 1 file(s)
Found 28 head motion-related components in a total of 64 components.
Traceback (most recent call last):
  File "/Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/ICA_AROMA.py", line 229, in <module>
    outDir)
  File "/Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/classification_plots.py", line 180, in classification_plot
    hist_kws={'alpha': 0.2})
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 231, in distplot
    kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 691, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 294, in _univariate_kdeplot
    x, y = _scipy_univariate_kde(data, bw, gridsize, cut, clip)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 366, in _scipy_univariate_kde
    kde = stats.gaussian_kde(data, bw_method=bw)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/stats/kde.py", line 208, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/stats/kde.py", line 540, in set_bandwidth
    self._compute_covariance()
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/stats/kde.py", line 552, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/linalg/basic.py", line 974, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix

**Comment by maartenmennes** [comment]
something is off either with your registration parameters or with the mixture modelling thresholding. Did you run melodic with the --Oalll and the --Ostats option?

**Comment by stephanwu89** [comment]
Yes, I tried that as well. The registration looks fine of the functional bold image.

**Comment by maartenmennes** [comment]
based on this: "The MELODIC directory does not contain the required 'stats' folder. Mixture modeling on the Z-statistical maps will be run." it looks like you're not providing the melodic run with the --Oall or the --Ostats option?

**Comment by stephanwu89** [comment]
With that option it changed to:

------------------------------- RUNNING ICA-AROMA ------------------------------- 
--------------- 'ICA-based Automatic Removal Of Motion Artifacts' --------------- 

Step 1) MELODIC
  - The existing/specified MELODIC directory will be used.
Step 2) Automatic classification of the components
  - registering the spatial maps to MNI
  - extracting the CSF & Edge fraction features
     - The spatial map of component 1 is empty. Please check!
     - The spatial map of component 2 is empty. Please check!
     - The spatial map of component 3 is empty. Please check!
     - The spatial map of component 4 is empty. Please check!
     - The spatial map of component 5 is empty. Please check!
     - The spatial map of component 6 is empty. Please check!
     - The spatial map of component 7 is empty. Please check!
     - The spatial map of component 8 is empty. Please check!
     - The spatial map of component 9 is empty. Please check!
     - The spatial map of component 10 is empty. Please check!
     - The spatial map of component 11 is empty. Please check!
     - The spatial map of component 12 is empty. Please check!
     - The spatial map of component 13 is empty. Please check!
     - The spatial map of component 14 is empty. Please check!
     - The spatial map of component 15 is empty. Please check!
     - The spatial map of component 16 is empty. Please check!
     - The spatial map of component 17 is empty. Please check!
     - The spatial map of component 18 is empty. Please check!
     - The spatial map of component 19 is empty. Please check!
     - The spatial map of component 20 is empty. Please check!
  - extracting the Maximum RP correlation feature
  - extracting the High-frequency content feature
  - classification
Found 1 file(s)
Found 19 head motion-related components in a total of 20 components.
Traceback (most recent call last):
  File "/Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/ICA_AROMA.py", line 229, in <module>
    outDir)
  File "/Users/neurolab/Desktop/Stephan/Programmes/ICA-AROMA-master/classification_plots.py", line 180, in classification_plot
    hist_kws={'alpha': 0.2})
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 231, in distplot
    kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 691, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 294, in _univariate_kdeplot
    x, y = _scipy_univariate_kde(data, bw, gridsize, cut, clip)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/seaborn/distributions.py", line 366, in _scipy_univariate_kde
    kde = stats.gaussian_kde(data, bw_method=bw)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/stats/kde.py", line 208, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/stats/kde.py", line 540, in set_bandwidth
    self._compute_covariance()
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/stats/kde.py", line 552, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/Users/neurolab/Library/Python/2.7/lib/python/site-packages/scipy/linalg/basic.py", line 974, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix

**Comment by maartenmennes** [comment]
is there a way for you to send me a copy of this data? Preferably the preprocessed data with everything tarred up into a single archive.

**Comment by maartenmennes** [comment]
no, I would want to take a look and run a couple of things myself. If you can host on dropbox or something alike - password protected. Shoot me an email on m dot mennes at donders dot ru dot nl

**Comment by StephDocTUM** [comment]
did u receive it?
